CREATE TABLE control_calidad_proceso (
  id BIGINT NOT NULL AUTO_INCREMENT,
  id_orden_produccion BIGINT NOT NULL,
  id_ejecucion_batch BIGINT NULL,
  fecha_produccion DATE NOT NULL,
  tipo_producto VARCHAR(120) NULL,
  producto VARCHAR(150) NULL,
  lote VARCHAR(80) NULL,
  numero_marmita INT NULL,
  producto_en_proceso VARCHAR(150) NULL,
  ph_leche DECIMAL(5,2) NULL,
  acidez_leche DECIMAL(8,4) NULL,
  densidad_leche DECIMAL(8,4) NULL,
  grasa_leche DECIMAL(8,4) NULL,
  hora_inicio_hidrolisis TIME NULL,
  ph_inicial DECIMAL(5,2) NULL,
  hora_fin_hidrolisis TIME NULL,
  temperatura_inicial DECIMAL(6,2) NULL,
  temperatura_final DECIMAL(6,2) NULL,
  acidez_inicial DECIMAL(8,4) NULL,
  acidez_final DECIMAL(8,4) NULL,
  ph_final DECIMAL(5,2) NULL,
  brix_inicial DECIMAL(6,2) NULL,
  brix_final DECIMAL(6,2) NULL,
  presion DECIMAL(8,2) NULL,
  temperatura_coccion DECIMAL(6,2) NULL,
  temperatura_envasado DECIMAL(6,2) NULL,
  color_visual VARCHAR(80) NULL,
  sabor_visual VARCHAR(80) NULL,
  textura_visual VARCHAR(80) NULL,
  presentacion_envasado VARCHAR(120) NULL,
  fecha_vencimiento DATE NULL,
  liberado TINYINT(1) NOT NULL DEFAULT 0,
  retenido TINYINT(1) NOT NULL DEFAULT 0,
  id_realizado_por BIGINT NOT NULL,
  id_verificado_por BIGINT NULL,
  observaciones VARCHAR(500) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_control_calidad_proceso_orden (id_orden_produccion),
  KEY idx_control_calidad_proceso_batch (id_ejecucion_batch),
  KEY idx_control_calidad_proceso_fecha (fecha_produccion),
  KEY idx_control_calidad_proceso_realizado_por (id_realizado_por),
  KEY idx_control_calidad_proceso_verificado_por (id_verificado_por),
  CONSTRAINT fk_control_calidad_proceso_orden
    FOREIGN KEY (id_orden_produccion) REFERENCES orden_produccion(id) ON DELETE CASCADE,
  CONSTRAINT fk_control_calidad_proceso_batch
    FOREIGN KEY (id_ejecucion_batch) REFERENCES ejecucion_batch(id),
  CONSTRAINT fk_control_calidad_proceso_realizado_por
    FOREIGN KEY (id_realizado_por) REFERENCES usuario(id_usuario),
  CONSTRAINT fk_control_calidad_proceso_verificado_por
    FOREIGN KEY (id_verificado_por) REFERENCES usuario(id_usuario)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE control_peso_producto (
  id BIGINT NOT NULL AUTO_INCREMENT,
  id_orden_produccion BIGINT NOT NULL,
  id_ejecucion_batch BIGINT NULL,
  id_sku BIGINT NULL,
  fecha_control DATE NOT NULL,
  producto VARCHAR(150) NULL,
  marca VARCHAR(120) NULL,
  lote VARCHAR(80) NULL,
  fecha_vencimiento DATE NULL,
  presentacion VARCHAR(120) NULL,
  numero_tanda VARCHAR(40) NULL,
  rango_batches VARCHAR(80) NULL,
  peso_bruto_promedio DECIMAL(12,3) NULL,
  tara_promedio DECIMAL(12,3) NULL,
  peso_neto_promedio DECIMAL(12,3) NULL,
  apariencia_ok TINYINT(1) NULL,
  etiquetado_ok TINYINT(1) NULL,
  tapado_ok TINYINT(1) NULL,
  cantidad_por_caja INT NULL,
  liberado TINYINT(1) NOT NULL DEFAULT 0,
  retenido TINYINT(1) NOT NULL DEFAULT 0,
  id_realizado_por BIGINT NOT NULL,
  id_verificado_por BIGINT NULL,
  observaciones VARCHAR(500) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_control_peso_producto_orden (id_orden_produccion),
  KEY idx_control_peso_producto_batch (id_ejecucion_batch),
  KEY idx_control_peso_producto_sku (id_sku),
  KEY idx_control_peso_producto_fecha (fecha_control),
  KEY idx_control_peso_producto_realizado_por (id_realizado_por),
  KEY idx_control_peso_producto_verificado_por (id_verificado_por),
  CONSTRAINT fk_control_peso_producto_orden
    FOREIGN KEY (id_orden_produccion) REFERENCES orden_produccion(id) ON DELETE CASCADE,
  CONSTRAINT fk_control_peso_producto_batch
    FOREIGN KEY (id_ejecucion_batch) REFERENCES ejecucion_batch(id),
  CONSTRAINT fk_control_peso_producto_sku
    FOREIGN KEY (id_sku) REFERENCES catalogo_sku(id),
  CONSTRAINT fk_control_peso_producto_realizado_por
    FOREIGN KEY (id_realizado_por) REFERENCES usuario(id_usuario),
  CONSTRAINT fk_control_peso_producto_verificado_por
    FOREIGN KEY (id_verificado_por) REFERENCES usuario(id_usuario)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE control_peso_muestra (
  id BIGINT NOT NULL AUTO_INCREMENT,
  id_control_peso_producto BIGINT NOT NULL,
  numero_muestra INT NOT NULL,
  peso_bruto DECIMAL(12,3) NULL,
  tara DECIMAL(12,3) NULL,
  peso_neto DECIMAL(12,3) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_control_peso_muestra_numero (id_control_peso_producto, numero_muestra),
  CONSTRAINT fk_control_peso_muestra_control
    FOREIGN KEY (id_control_peso_producto) REFERENCES control_peso_producto(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
