-- V8: roles definitivos y catalogo de turnos.

ALTER TABLE usuario
  MODIFY rol ENUM(
    'OPERARIO',
    'JEFE_LINEA',
    'INGENIERO',
    'JEFE_PRODUCCION',
    'AUXILIAR_CALIDAD',
    'ANALISTA_LACTEOS',
    'JEFE_PLANTA',
    'GERENCIA',
    'ADMIN'
  ) NOT NULL;

UPDATE usuario
SET rol = 'JEFE_LINEA'
WHERE rol = 'OPERARIO';

UPDATE usuario
SET rol = 'JEFE_PRODUCCION'
WHERE rol = 'INGENIERO';

ALTER TABLE usuario
  MODIFY rol ENUM(
    'JEFE_PRODUCCION',
    'JEFE_LINEA',
    'AUXILIAR_CALIDAD',
    'ANALISTA_LACTEOS',
    'JEFE_PLANTA',
    'GERENCIA',
    'ADMIN'
  ) NOT NULL;

CREATE TABLE turno (
  id BIGINT NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(50) NOT NULL,
  hora_inicio TIME NOT NULL,
  hora_fin TIME NOT NULL,
  activo TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_turno_nombre (nombre)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
